package org.wallentines.mdcfg.sql;

import org.jetbrains.annotations.Nullable;

import java.util.Arrays;
import java.util.stream.IntStream;

/**
 * Stores a result of an insert or update operation
 */
public class UpdateResult {

    private final int[] affectedRows;

    @Nullable
    private final QueryResult generatedKeys;

    /**
     * Creates a new update result
     * @param affectedRows The number of affected rows per operation in the batch
     * @param generatedKeys The keys generated by an insert operation
     */
    public UpdateResult(int[] affectedRows, @Nullable QueryResult generatedKeys) {
        this.affectedRows = affectedRows;
        this.generatedKeys = generatedKeys;
    }

    /**
     * Returns true if keys were generated by the update operation, and those keys were returned
     * @return Whether the update result has generated keys
     */
    public boolean hasGeneratedKeys() {
        return generatedKeys != null;
    }

    /**
     * Gets the number of operations executed in the batch
     * @return The number of operations executed
     */
    public int batchCount() {
        return affectedRows.length;
    }

    /**
     * Gets the number of affected rows in the given operation
     * @param operation The operation number
     * @return The number of affected rows for that operation
     */
    public int getAffectedRows(int operation) {
        return affectedRows[operation];
    }

    /**
     * Gets a stream of all affected row counts
     * @return An int stream
     */
    public IntStream getAllAffectedRows() {
        return Arrays.stream(affectedRows);
    }

    /**
     * Gets the generated keys for this operation
     * @return A QueryResult containing the generated keys, or null
     */
    @Nullable
    public QueryResult getGeneratedKeys() {
        return generatedKeys;
    }

}
